import { Mona_Sans } from "next/font/google"
import "./globals.css";

const monaSans = Mona_Sans({
  subsets: ["latin"],
  variable: "--font-mona",
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body
        className={`${monaSans.variable} antialiased scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
